version: '3.4'
services:
  rasa-server:
    image: rasa-demo:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
      - ./models:/app/models
    command: base -c "rn -rf models/* && rasa train && rasa run --enable-api --cors \"*\" --debug"
    ports:
      - '5005:5005'
    networks:
      - all

  rasa-actiosn:
    image:
    working_dir: /app
    build: "./"
    restart: always
    volumes:
      - ./actions:/app/actions
    command: ["rasa", "run", "actions"]
    ports:
      - '5055:5055'
    networks:
      - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
